#pragma once

#include "driver/gpio.h"
#include "esp_adc/adc_oneshot.h"

/* CAN */
#define CEM_CAN_TX_GPIO GPIO_NUM_45
#define CEM_CAN_RX_GPIO GPIO_NUM_48

/* I/O */
#define CEM_SOFTWARE_KILL_GPIO GPIO_NUM_35

/* ANALOG INPUTS */
#define CEM_ADC1_UNIT ADC_UNIT_2
#define CEM_ADC1_CHANNEL ADC_CHANNEL_3

#define CEM_ADC2_UNIT ADC_UNIT_2
#define CEM_ADC2_CHANNEL ADC_CHANNEL_0

#define CEM_ADC3_UNIT ADC_UNIT_1
#define CEM_ADC3_CHANNEL ADC_CHANNEL_9

#define CEM_ADC4_UNIT ADC_UNIT_1
#define CEM_ADC4_CHANNEL ADC_CHANNEL_8

#define CEM_ADC5_UNIT ADC_UNIT_2
#define CEM_ADC5_CHANNEL ADC_CHANNEL_6

#define CEM_ADC6_UNIT ADC_UNIT_2
#define CEM_ADC6_CHANNEL ADC_CHANNEL_5

#define CEM_ADC7_UNIT ADC_UNIT_2
#define CEM_ADC7_CHANNEL ADC_CHANNEL_7

#define CEM_ADC8_UNIT ADC_UNIT_1
#define CEM_ADC8_CHANNEL ADC_CHANNEL_7